version: '3'

services:
  app:
    build: ./
    volumes:
      - ./:/app
    container_name: kms-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    #      - cache
    links:
      - db
    #      - cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    #      - REDIS_HOST=${REDIS_HOST}
    #      - REDIS_PORT=${REDIS_PORT}
    networks:
      - kms_network

  db:
    image: postgres:latest
    container_name: kms-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - kms_network

#  cache:
#    image: redis:latest
#    container_name: kms-cache
#    ports:
#      - "6379:6379"
#    restart: always
#    networks:
#      - kms_network

networks:
  kms_network:
    driver: bridge